---
title: "ipsci"
author: "Jai Jeffryes"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proposal

Assessment of the state of science is a requirement for
research. Assessment of intellectual property is a requirement for
capitalization of knowledge for profit. This project explores tools
for surveying patent data and research data in order to develop
methods for making these assessments.

The project begins with an examination of data from NASA, whose open
data portal includes a dataset of NASA patents. The format is a
delimited text file. The data include a patent case number and
title. Exploration of this dataset may include unsupervised learning
to yield topics of patents.

The World Intellectual Property Organization (WIPO) publishes The WIPO
Manual on Open Source Patent Analytics with instruction for data
interrogation useful for subsequent parts of this project. The project
will continue with a more detailed exploration of patent cases opened
by NASA with a view to revealing more topics from within patent case
data other than the title of the case, perhaps from the patent
application, for example.

There are at least two data sources for patent data. The primary data
source is the U.S. Patent and Trademark Office (USPTO), whose Open
Data Portal publishes many datasets in various formats. USPTO also
supplies APIs for patent data retrieval. Besides these APIs, there is
at least one potentially useful third party API called
PatentsView.

One resource for research publications is the Public Library of
Science (PLOS), who publish open access peer reviewed articles. The
inventory of articles seems limited, but appears to enable an
introduction to text mining of research papers. This project will take
some of the interesting topics identified in its earlier parts and
search for research articles related to those topics. Text mining of
PLOS will utilize an R package not covered in class, rplos, which
provides a programmatic interface to the Solr based search API
provided by PLOS. Solr is an open source search platform built on
Apache Lucerne.

## Resources
### References
- [The WIPO Manual on Open Source Patent Analytics](https://wipo-analytics.github.io). An end-to-end guide for information retrieval for patents and research papers.

### Agencies and services
- [WIPO](https://www.wipo.int/portal/en/index.html). The World Intellectual Property Organization.
- [Public Library of Science](https://www.plos.org). PLOS. 200K+ open access peer-reviewed journal articles.
- [rOpenSci](https://ropensci.org). Non-profit that addresses reproducibility of scientific data retrieval. A raft of R packages for working with scientific data sources and supporting research. Leadership includes Jenny Bryan and advisors include Hadley Wickham. Blog, tutorials, and videos.
- [One World Analytics](http://oneworldanalytics.com). Analyzes social and environmental issues using text mining, statistics, geographic mapping and network visualisation.

### NASA
- [NASA's Open Data Portal](https://data.nasa.gov).
- [NASA Patents](https://data.nasa.gov/Raw-Data/NASA-Patents/gquh-watm).

### US patent data
- [USPTO Open Data Portal](https://developer.uspto.gov). United States Patent and Trademark Office data products. Bulk downloads, APIs, analytics, etc.
- [PatentsView](http://www.patentsview.org/). Secondary source, with dataset downloads and APIs.

### R packages
- `rplos` [Vignette](https://cran.r-project.org/web/packages/rplos/rplos.pdf). Interface to the Solr based search [API](http://api.plos.org/) for PLOS journals. Functions search for articles, retrieve articles, make plots, do faceted searches, highlight searches, and present results of highlighted searches in a browser.
- `fulltext` [Vignette](https://ropensci.org/tutorials/fulltext_tutorial/). Facilitates text mining with an emphasis on open access journals. The vignette provides examples.

### APIs
- [PLOS API](http://api.plos.org/). Documentation, articles, frequently asked questions.

### Examples
- [PLos Article Classification](https://github.com/akud/PLoS-Article-Classification). A Python project on GitHub using machine learning to classify scientific articles by subject.
- [Open NASA Data from API to Data Analysis](https://www.youtube.com/watch?v=JoaQctLP2Cg). YouTube video by Noemi Derzsy, NASA Datanaut, from the 2017 NYC SpaceApps Conference. Easy introduction to data obtainable from NASA.